#pragma once
// Game ->
#define ADDRESS_GAMEMANAGER 0x4EBD3C8
#define ADDRESS_GAMERENDERER 0x4DA32C0
#define ADDRESS_INTERFACE 0x4EBBCC0
#define ADDRESS_STATUSMANAGER 0x36C9DC8
#define ADDRESS_NAMEMANAGER 0x4E77AF0
#define ADDRESS_NETWORKMANAGER 0x4D96538
#define ADDRESS_LOCALPLAYER 0x4EBD3D0
#define ADDRESS_GADGETMANAGER 0x4D96538
#define ADDRESS_STATUSMANAGER 0x4E7F810

// Game -> Interface ->
#define OFFSET_INTERFACE 0x400
#define OFFSET_INTERFACE_INCROSS 0x398 // Interface ->

// Game -> GameRenderer ->
#define OFFSET_GAMERENDERER_DEREF 0x0
#define OFFSET_GAMERENDERER_ENGINELINK 0x120 // Deref ->
#define OFFSET_ENGINELINK_ENGINE 0x230 // EngineLink ->
#define OFFSET_ENGINE_CAMERA 0x40 // Engine ->

// Game -> GameRenderer -> Camera ->
#define OFFSET_CAMERA_VIEWRIGHT 0xB0
#define OFFSET_CAMERA_VIEWUP 0xC0
#define OFFSET_CAMERA_VIEWFORWARD 0xD0
#define OFFSET_CAMERA_VIEWTRANSLATION 0xE0
#define OFFSET_CAMERA_VIEWFOVX 0xF0
#define OFFSET_CAMERA_VIEWFOVY 0x104

// Game -> GameManager ->
#define OFFSET_GAMEMANAGER_ENTITYLIST 0xC8

// Game -> GameManager -> EntityList -> INDEX -> Entity ->
#define OFFSET_ENTITY_ENTITYINFO 0x18
#define OFFSET_ENTITYINFO_MAINCOMPONENT 0xA8 // EntityInfo ->
#define OFFSET_MAINCOMPONENT_CHILDCOMPONENT 0x8 // MainComponent ->
#define OFFSET_CHILDCOMPONENT_HEALTH 0x148 // ChildComponent ->

#define OFFSET_ENTITY_PLAYERINFO 0x2B8
#define OFFSET_PLAYERINFO_MAINCOMPONENT 0x0 // PlayerInfo ->
#define OFFSET_MAINCOMPONENT_TEAMID 0x146 // MainComponent ->

#define OFFSET_MAINCOMPONENT_WEAPONCOMPONENT 0x38 // MainComponent ->
#define OFFSET_WEAPONCOMPONENT_WEAPONPROCESSOR 0xF0 // WeaponComponent ->
#define OFFSET_WEAPONPROCESSOR_WEAPON 0x0 // WeaponProcessor ->
#define OFFSET_WEAPON_WEAPONINFO1 0x120 // Weapon ->
#define OFFSET_WEAPON_WEAPONINFO2 0x110 // Weapon ->
#define OFFSET_WEAPONINFO_RECOIL 0xA8 // WeaponInfo ->
#define OFFSET_WEAPONINFO_SPREAD 0x70 // WeaponInfo ->

#define OFFSET_ENTITY_FEET 0x1D0
#define OFFSET_ENTITY_NECK 0x170
#define OFFSET_ENTITY_HEAD 0x180
#define OFFSET_ENTITY_RIGHTHAND 0x1A0
#define OFFSET_ENTITY_LEFTHAND 0x1E0

// Game -> GameManager -> EntityList -> INDEX -> Entity -> EntityInfo -> MainComponent ->
#define OFFSET_MAINCOMPONENT_ESPCHAIN1 0x30
#define OFFSET_ESPCHAIN1_ESPCHAIN2 0x178 // ESPCHAIN1 ->
#define OFFSET_ESPCHAIN2_ESPCHAIN3 0x2E4 // ESPCHAIN2 ->

// Game
#define OFFSET_BONE_LEFT_TOE 0x378
#define OFFSET_BONE_LEFT_ANKLE 0x358
#define OFFSET_BONE_LEFT_KNEE 0x3D8
#define OFFSET_BONE_LEFT_HIP 0x3B8
#define OFFSET_BONE_RIGHT_TOE 0x458
#define OFFSET_BONE_RIGHT_ANKLE 0x438
#define OFFSET_BONE_RIGHT_KNEE 0x4B8
#define OFFSET_BONE_RIGHT_HIP 0x498
#define OFFSET_BONE_LEFT_SHOULDER 0x598
#define OFFSET_BONE_LEFT_LBOW 0x5B8
#define OFFSET_BONE_LEFT_HAND 0x5D8
#define OFFSET_BONE_RIGHT_SHOULDER 0xF78
#define OFFSET_BONE_RIGHT_LBOW 0xF98
#define OFFSET_BONE_RIGHT_HAND 0xFB8
